name: Generate Snake Animation

on:
  # Her 12 saatte bir otomatik çalıştır
  schedule:
    - cron: "0 */12 * * *"
  
  # Manuel çalıştırma seçeneği
  workflow_dispatch:
  
  # Her push'ta çalıştır
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Repository'yi checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake animasyonunu oluştur
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: therivalsx
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Output klasörünü oluştur ve dosyaları taşı
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
